name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  is-docker-installed:
    runs-on: [self-hosted, Linux, X64]
    steps:
      - name: Проверка докера...
        run: docker version

  deploy-crm:
    needs: is-docker-installed
    runs-on: [self-hosted, Linux, X64]
    steps:
      - name: Клонирование репозитория...
        uses: actions/checkout@v3

      - name: Остановка старых контейнеров...
        run: docker compose down || true

      - name: Пересборка и запуск приложения...
        run: |
          docker compose build --no-cache
          docker compose up -d